dist: trusty

sudo: false  # builds will run on Docker infrastructure!

language: scala

scala:
  - 2.12.1
  
jdk:
  - oraclejdk8
  - openjdk8
  
branches:
  only:
    - develop
    - master
    - /(release)-.*$/
    
before_install:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out local.pubring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in credentials.sbt.enc -out local.credentials.sbt -d
    
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile
  - sbt ++$TRAVIS_SCALA_VERSION coverage test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport codacyCoverage  # uses decrypted CODACY_PROJECT_TOKEN
  #- scripts/publish.sh
  
env:
  global:
    - secure: "uzS5ljC6EvkuhIi9qR3KdwUUuKwzeanLAm9emIxmFn/TX7on0BA6wL+qOzjupHiq5X6SRCD4taXJ7mLfps3mLthD1J+AsgJbCa8i4jz7wXhzv1azHOPaaM+ywjalDajwj6JAPpw3nKtnDjVIIiQ/YTcKonkQqtLRpYyoigJwrgj9X4PbUZPA4D1fuRfvqK1oK3YXMry6f/XKX0Gy0ydJ7e0ZP3JGSe62sbK8RXGlnFi+mJ4oXspqNPPuUkGI7P3RNAOq7a8vcHIGgh267rnDzrnVK50YxP294zA2KaT2nfGBSQTSJH4dd3R7STUHQh71yxeG3na6WF84em5bRkI5vvLqgOOJ140LdIqC6Ez56U209OGs+KPT7Z8KasU4mgSMnNY7GpYGiPDiiawunouUsqNLPsOht3BVrgfsdtsPKW5XAKvRWaCmuHzOykf29VejwTBSzvhRl86ro0XaJo4E4hdYkzNfN9h7yDck1llfPp6fNT1MtVhjn7pECXrY+4R43/lAw4A/ZivK74wXi0SFJTfvAJf+PBs61fbQL2aVQxzoyG8RKut0IOp7UiZIrzfjy0u2f8H4xpOQPLtv1K93yyIV7ETo7JOuGzg7u6q09K7Yz5espemIodkuNYDZ8NcoDwNdoGJj+TEIQgTWcrTTXNAbyWxLRtln0Q6qgc6BK+k="
    - secure: "pGgwZk1yM8WnV6b0p5kK0PFz2uVcOr/KfBkfeJQGtV+Xfs0ZGEoliPTec/m9hVcuxzUeKYCaunPVFgYr8+Si0HosowE+kPdcbpvaWZlZIDZIJa08CPLtYlbdDhHQrToc82louQ/E/WWxqCYhYFsyaL7MPtqytj7s9xsXrx+PR8fTKuhYakCB7QkkkZvx+Vr8di0LCHJP98Mp2nMewtZ2D5tw8310Es8gmTMEnnxCnS0lG5gsbjroUkNnRi5LDacYtnkWHOL+Hk1WCTPOlYauMueF4ECk2Abl8EkiR8n1qYylFhnMcEYm3D0DMxNHh0LACsBmOg9zzmwTz+QSlY7kRnOc9Wf1gLMiF+h+BeAQwdhZdK9xFOLoJRGxH10jSiGPjZ8ynDTUA/3PbwPQZ27YOuBXvWJ+HpyZs4a/oaUENCJ6V5zJxQgB5efW+T4ysZcnD5oCheLiPCeM5cl8aQb0+IG54sCiMvZoR+2BK/dvuI2NhED1tRMlEbTFjgU7rCKak1LeQaiTt1zCeL8ezf3pkbO7GUXTsYBuugaFRbUS4P6N9RWl+5WdOO4fnYu1yRNTbR64b8NCFjF4wGH+/6/ZsHlo285SqmPBka9Miu/Zg3BlSQasmENChxSgfbiz9v/ZjJoY7szFjRlnUvy/np1bwsLD4qtu3U0Zewmgnwg3MLk="

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
